#!/bin/bash
tail -n +5 "$0" | dmenu -i -l 20 | cut -d\  -f1 - | sed -z "s/\n//g" | xclip -i -selection clipboard
<<EOF

😀 Grinning Face
😃 Grinning Face with Big Eyes
😄 Grinning Face with Smiling Eyes
😁 Beaming Face with Smiling Eyes
😆 Grinning Squinting Face
😅 Grinning Face with Sweat
🤣 Rolling on the Floor Laughing
😂 Face with Tears of Joy
🙂 Slightly Smiling Face
🙃 Upside-Down Face
🫠 Melting Face
😉 Winking Face
😊 Smiling Face with Smiling Eyes
😇 Smiling Face with Halo
🥰 Smiling Face with Hearts
😍 Smiling Face with Heart-Eyes
🤩 Star-Struck
😘 Face Blowing a Kiss
😗 Kissing Face
☺️ Smiling Face
😚 Kissing Face with Closed Eyes
😙 Kissing Face with Smiling Eyes
🥲 Smiling Face with Tear
😋 Face Savoring Food
😛 Face with Tongue
😜 Winking Face with Tongue
🤪 Zany Face
😝 Squinting Face with Tongue
🤑 Money-Mouth Face
🤗 Smiling Face with Open Hands
🤭 Face with Hand Over Mouth
🫢 Face with Open Eyes and Hand Over Mouth
🫣 Face with Peeking Eye
🤫 Shushing Face
🤔 Thinking Face
🫡 Saluting Face
🤐 Zipper-Mouth Face
🤨 Face with Raised Eyebrow
😐 Neutral Face
😑 Expressionless Face
😶 Face Without Mouth
🫥 Dotted Line Face
😏 Smirking Face
😒 Unamused Face
🙄 Face with Rolling Eyes
😬 Grimacing Face
🤥 Lying Face
😌 Relieved Face
😔 Pensive Face
😪 Sleepy Face
🤤 Drooling Face
😴 Sleeping Face
😷 Face with Medical Mask
🤒 Face with Thermometer
🤕 Face with Head-Bandage
🤢 Nauseated Face
🤮 Face Vomiting
🤧 Sneezing Face
🥵 Hot Face
🥶 Cold Face
🥴 Woozy Face
😵 Face with Crossed-Out Eyes
🤯 Exploding Head
🤠 Cowboy Hat Face
🥳 Partying Face
🥸 Disguised Face
😎 Smiling Face with Sunglasses
🤓 Nerd Face
🧐 Face with Monocle
😕 Confused Face
🫤 Face with Diagonal Mouth
😟 Worried Face
🙁 Slightly Frowning Face
☹️ Frowning Face
😮 Face with Open Mouth
😯 Hushed Face
😲 Astonished Face
😳 Flushed Face
🥺 Pleading Face
🥹 Face Holding Back Tears
😦 Frowning Face with Open Mouth
😧 Anguished Face
😨 Fearful Face
😰 Anxious Face with Sweat
😥 Sad but Relieved Face
😢 Crying Face
😭 Loudly Crying Face
😱 Face Screaming in Fear
😖 Confounded Face
😣 Persevering Face
😞 Disappointed Face
😓 Downcast Face with Sweat
😩 Weary Face
😫 Tired Face
🥱 Yawning Face
😤 Face with Steam From Nose
😡 Enraged Face
😠 Angry Face
🤬 Face with Symbols on Mouth
😈 Smiling Face with Horns
👿 Angry Face with Horns
💀 Skull
☠️ Skull and Crossbones
💩 Pile of Poo
🤡 Clown Face
👹 Ogre
👺 Goblin
👻 Ghost
👽 Alien
👾 Alien Monster
🤖 Robot
😺 Grinning Cat
😸 Grinning Cat with Smiling Eyes
😹 Cat with Tears of Joy
😻 Smiling Cat with Heart-Eyes
😼 Cat with Wry Smile
😽 Kissing Cat
🙀 Weary Cat
😿 Crying Cat
😾 Pouting Cat
💋 Kiss Mark
👋 Waving Hand
🤚 Raised Back of Hand
🖐️ Hand with Fingers Splayed
✋ Raised Hand
🖖 Vulcan Salute
🫱 Rightwards Hand
🫲 Leftwards Hand
🫳 Palm Down Hand
🫴 Palm Up Hand
👌 OK Hand
🤌 Pinched Fingers
🤏 Pinching Hand
✌️ Victory Hand
🤞 Crossed Fingers
🫰 Hand with Index Finger and Thumb Crossed
🤟 Love-You Gesture
🤘 Sign of the Horns
🤙 Call Me Hand
👈 Backhand Index Pointing Left
👉 Backhand Index Pointing Right
👆 Backhand Index Pointing Up
🖕 Middle Finger
👇 Backhand Index Pointing Down
☝️ Index Pointing Up
🫵 Index Pointing at the Viewer
👍 Thumbs Up
👎 Thumbs Down
✊ Raised Fist
👊 Oncoming Fist
🤛 Left-Facing Fist
🤜 Right-Facing Fist
👏 Clapping Hands
🙌 Raising Hands
🫶 Heart Hands
👐 Open Hands
🤲 Palms Up Together
🤝 Handshake
🙏 Folded Hands
✍️ Writing Hand
💅 Nail Polish
🤳 Selfie
💪 Flexed Biceps
🦾 Mechanical Arm
🦿 Mechanical Leg
🦵 Leg
🦶 Foot
👂 Ear
🦻 Ear with Hearing Aid
👃 Nose
🧠 Brain
🫀 Anatomical Heart
🫁 Lungs
🦷 Tooth
🦴 Bone
👀 Eyes
👁️ Eye
👅 Tongue
👄 Mouth
🫦 Biting Lip
👶 Baby
🧒 Child
👦 Boy
👧 Girl
🧑 Person
👱 Person: Blond Hair
👨 Man
🧔 Person: Beard
👩 Woman
🧓 Older Person
👴 Old Man
👵 Old Woman
🙍 Person Frowning
🙎 Person Pouting
🙅 Person Gesturing No
🙆 Person Gesturing OK
💁 Person Tipping Hand
🙋 Person Raising Hand
🧏 Deaf Person
🙇 Person Bowing
🤦 Person Facepalming
🤷 Person Shrugging
👮 Police Officer
🕵️ Detective
💂 Guard
🥷 Ninja
👷 Construction Worker
🫅 Person with Crown
🤴 Prince
👸 Princess
👳 Person Wearing Turban
👲 Person with Skullcap
🧕 Woman with Headscarf
🤵 Person in Tuxedo
👰 Person with Veil
🤰 Pregnant Woman
🫃 Pregnant Man
🫄 Pregnant Person
🤱 Breast-Feeding
👼 Baby Angel
🎅 Santa Claus
🤶 Mrs. Claus
🦸 Superhero
🦹 Supervillain
🧙 Mage
🧚 Fairy
🧛 Vampire
🧜 Merperson
🧝 Elf
🧞 Genie
🧟 Zombie
🧌 Troll
💆 Person Getting Massage
💇 Person Getting Haircut
🚶 Person Walking
🧍 Person Standing
🧎 Person Kneeling
🏃 Person Running
💃 Woman Dancing
🕺 Man Dancing
🕴️ Person in Suit Levitating
👯 People with Bunny Ears
🧖 Person in Steamy Room
🧘 Person in Lotus Position
👭 Women Holding Hands
👫 Woman and Man Holding Hands
👬 Men Holding Hands
💏 Kiss
🗣️ Speaking Head
👤 Bust in Silhouette
👥 Busts in Silhouette
🫂 People Hugging
👣 Footprints
🧳 Luggage
🌂 Closed Umbrella
☂️ Umbrella
🎃 Jack-O-Lantern
🧵 Thread
🧶 Yarn
👓 Glasses
🕶️ Sunglasses
🥽 Goggles
🥼 Lab Coat
🦺 Safety Vest
👔 Necktie
👕 T-Shirt
👖 Jeans
🧣 Scarf
🧤 Gloves
🧥 Coat
🧦 Socks
👗 Dress
👘 Kimono
🥻 Sari
🩱 One-Piece Swimsuit
🩲 Briefs
🩳 Shorts
👙 Bikini
👚 Woman’s Clothes
👛 Purse
👜 Handbag
👝 Clutch Bag
🎒 Backpack
🩴 Thong Sandal
👞 Man’s Shoe
👟 Running Shoe
🥾 Hiking Boot
🥿 Flat Shoe
👠 High-Heeled Shoe
👡 Woman’s Sandal
🩰 Ballet Shoes
👢 Woman’s Boot
👑 Crown
👒 Woman’s Hat
🎩 Top Hat
🎓 Graduation Cap
🧢 Billed Cap
🪖 Military Helmet
⛑️ Rescue Worker’s Helmet
💄 Lipstick
💍 Ring
💼 Briefcase
🩸 Drop of Blood
💌 Love Letter
🕳️ Hole
💣 Bomb
🛀 Person Taking Bath
🛌 Person in Bed
🔪 Kitchen Knife
🏺 Amphora
🗺️ World Map
🧭 Compass
🧱 Brick
💈 Barber Pole
🦽 Manual Wheelchair
🦼 Motorized Wheelchair
🛢️ Oil Drum
🛎️ Bellhop Bell
🧳 Luggage
⌛ Hourglass Done
⏳ Hourglass Not Done
⌚ Watch
⏰ Alarm Clock
⏱️ Stopwatch
⏲️ Timer Clock
🕰️ Mantelpiece Clock
🌡️ Thermometer
⛱️ Umbrella on Ground
🧨 Firecracker
🎈 Balloon
🎉 Party Popper
🎊 Confetti Ball
🎎 Japanese Dolls
🎏 Carp Streamer
🎐 Wind Chime
🧧 Red Envelope
🎀 Ribbon
🎁 Wrapped Gift
🤿 Diving Mask
🪀 Yo-Yo
🪁 Kite
🔮 Crystal Ball
🪄 Magic Wand
🧿 Nazar Amulet
🪬 Hamsa
🕹️ Joystick
🧸 Teddy Bear
🪅 Piñata
🪆 Nesting Dolls
🖼️ Framed Picture
🧵 Thread
🪡 Sewing Needle
🧶 Yarn
🪢 Knot
🛍️ Shopping Bags
📿 Prayer Beads
💎 Gem Stone
📯 Postal Horn
🎙️ Studio Microphone
🎚️ Level Slider
🎛️ Control Knobs
📻 Radio
🪕 Banjo
📱 Mobile Phone
📲 Mobile Phone with Arrow
☎️ Telephone
📞 Telephone Receiver
📟 Pager
📠 Fax Machine
🔋 Battery
🔌 Electric Plug
💻 Laptop
🖥️ Desktop Computer
🖨️ Printer
⌨️ Keyboard
🖱️ Computer Mouse
🖲️ Trackball
💽 Computer Disk
💾 Floppy Disk
💿 Optical Disk
📀 DVD
🧮 Abacus
🎥 Movie Camera
🎞️ Film Frames
📽️ Film Projector
📺 Television
📷 Camera
📸 Camera with Flash
📹 Video Camera
📼 Videocassette
🔍 Magnifying Glass Tilted Left
🔎 Magnifying Glass Tilted Right
🕯️ Candle
💡 Light Bulb
🔦 Flashlight
🏮 Red Paper Lantern
🪔 Diya Lamp
📔 Notebook with Decorative Cover
📕 Closed Book
📖 Open Book
📗 Green Book
📘 Blue Book
📙 Orange Book
📚 Books
📓 Notebook
📒 Ledger
📃 Page with Curl
📜 Scroll
📄 Page Facing Up
📰 Newspaper
🗞️ Rolled-Up Newspaper
📑 Bookmark Tabs
🔖 Bookmark
🏷️ Label
💰 Money Bag
🪙 Coin
💴 Yen Banknote
💵 Dollar Banknote
💶 Euro Banknote
💷 Pound Banknote
💸 Money with Wings
💳 Credit Card
🧾 Receipt
✉️ Envelope
📧 E-Mail
📨 Incoming Envelope
📩 Envelope with Arrow
📤 Outbox Tray
📥 Inbox Tray
📦 Package
📫 Closed Mailbox with Raised Flag
📪 Closed Mailbox with Lowered Flag
📬 Open Mailbox with Raised Flag
📭 Open Mailbox with Lowered Flag
📮 Postbox
🗳️ Ballot Box with Ballot
✏️ Pencil
✒️ Black Nib
🖋️ Fountain Pen
🖊️ Pen
🖌️ Paintbrush
🖍️ Crayon
📝 Memo
📁 File Folder
📂 Open File Folder
🗂️ Card Index Dividers
📅 Calendar
📆 Tear-Off Calendar
🗒️ Spiral Notepad
🗓️ Spiral Calendar
📇 Card Index
📈 Chart Increasing
📉 Chart Decreasing
📊 Bar Chart
📋 Clipboard
📌 Pushpin
📍 Round Pushpin
📎 Paperclip
🖇️ Linked Paperclips
📏 Straight Ruler
📐 Triangular Ruler
✂️ Scissors
🗃️ Card File Box
🗄️ File Cabinet
🗑️ Wastebasket
🔒 Locked
🔓 Unlocked
🔏 Locked with Pen
🔐 Locked with Key
🔑 Key
🗝️ Old Key
🔨 Hammer
🪓 Axe
⛏️ Pick
⚒️ Hammer and Pick
🛠️ Hammer and Wrench
🗡️ Dagger
⚔️ Crossed Swords
🔫 Water Pistol
🪃 Boomerang
🛡️ Shield
🪚 Carpentry Saw
🔧 Wrench
🪛 Screwdriver
🔩 Nut and Bolt
⚙️ Gear
🗜️ Clamp
⚖️ Balance Scale
🦯 White Cane
🔗 Link
⛓️ Chains
🪝 Hook
🧰 Toolbox
🧲 Magnet
🪜 Ladder
⚗️ Alembic
🧪 Test Tube
🧫 Petri Dish
🧬 DNA
🔬 Microscope
🔭 Telescope
📡 Satellite Antenna
💉 Syringe
🩸 Drop of Blood
💊 Pill
🩹 Adhesive Bandage
🩼 Crutch
🩺 Stethoscope
🚪 Door
🪞 Mirror
🪟 Window
🛏️ Bed
🛋️ Couch and Lamp
🪑 Chair
🚽 Toilet
🪠 Plunger
🚿 Shower
🛁 Bathtub
🪤 Mouse Trap
🪒 Razor
🧴 Lotion Bottle
🧷 Safety Pin
🧹 Broom
🧺 Basket
🧻 Roll of Paper
🪣 Bucket
🧼 Soap
🪥 Toothbrush
🧽 Sponge
🧯 Fire Extinguisher
🛒 Shopping Cart
🚬 Cigarette
⚰️ Coffin
🪦 Headstone
⚱️ Funeral Urn
🗿 Moai
🪧 Placard
🪪 Identification Card
🚰 Potable Water
💘 Heart with Arrow
💝 Heart with Ribbon
💖 Sparkling Heart
💗 Growing Heart
💓 Beating Heart
💞 Revolving Hearts
💕 Two Hearts
💟 Heart Decoration
❣️ Heart Exclamation
💔 Broken Heart
❤️‍🔥 Heart on Fire
❤️‍🩹 Mending Heart
❤️ Red Heart
🧡 Orange Heart
💛 Yellow Heart
💚 Green Heart
💙 Blue Heart
💜 Purple Heart
🤎 Brown Heart
🖤 Black Heart
🤍 White Heart
💯 Hundred Points
💢 Anger Symbol
💬 Speech Balloon
👁️‍🗨️ Eye in Speech Bubble
🗨️ Left Speech Bubble
🗯️ Right Anger Bubble
💭 Thought Balloon
💤 Zzz
💮 White Flower
♨️ Hot Springs
💈 Barber Pole
🛑 Stop Sign
🕛 Twelve O’Clock
🕧 Twelve-Thirty
🕐 One O’Clock
🕜 One-Thirty
🕑 Two O’Clock
🕝 Two-Thirty
🕒 Three O’Clock
🕞 Three-Thirty
🕓 Four O’Clock
🕟 Four-Thirty
🕔 Five O’Clock
🕠 Five-Thirty
🕕 Six O’Clock
🕡 Six-Thirty
🕖 Seven O’Clock
🕢 Seven-Thirty
🕗 Eight O’Clock
🕣 Eight-Thirty
🕘 Nine O’Clock
🕤 Nine-Thirty
🕙 Ten O’Clock
🕥 Ten-Thirty
🕚 Eleven O’Clock
🕦 Eleven-Thirty
🌀 Cyclone
♠️ Spade Suit
♥️ Heart Suit
♦️ Diamond Suit
♣️ Club Suit
🃏 Joker
🀄 Mahjong Red Dragon
🎴 Flower Playing Cards
🔇 Muted Speaker
🔈 Speaker Low Volume
🔉 Speaker Medium Volume
🔊 Speaker High Volume
📢 Loudspeaker
📣 Megaphone
📯 Postal Horn
🔔 Bell
🔕 Bell with Slash
🎵 Musical Note
🎶 Musical Notes
💹 Chart Increasing with Yen
🛗 Elevator
🏧 ATM Sign
🚮 Litter in Bin Sign
🚰 Potable Water
♿ Wheelchair Symbol
🚹 Men’s Room
🚺 Women’s Room
🚻 Restroom
🚼 Baby Symbol
🚾 Water Closet
⚠️ Warning
🚸 Children Crossing
⛔ No Entry
🚫 Prohibited
🚳 No Bicycles
🚭 No Smoking
🚯 No Littering
🚱 Non-Potable Water
🚷 No Pedestrians
📵 No Mobile Phones
🔞 No One Under Eighteen
☢️ Radioactive
☣️ Biohazard
⬆️ Up Arrow
↗️ Up-Right Arrow
➡️ Right Arrow
↘️ Down-Right Arrow
⬇️ Down Arrow
↙️ Down-Left Arrow
⬅️ Left Arrow
↖️ Up-Left Arrow
↕️ Up-Down Arrow
↔️ Left-Right Arrow
↩️ Right Arrow Curving Left
↪️ Left Arrow Curving Right
⤴️ Right Arrow Curving Up
⤵️ Right Arrow Curving Down
🔃 Clockwise Vertical Arrows
🔄 Counterclockwise Arrows Button
🔙 Back Arrow
🔚 End Arrow
🔛 On! Arrow
🔜 Soon Arrow
🔝 Top Arrow
🛐 Place of Worship
⚛️ Atom Symbol
🕉️ Om
✡️ Star of David
☸️ Wheel of Dharma
☯️ Yin Yang
✝️ Latin Cross
☦️ Orthodox Cross
☪️ Star and Crescent
☮️ Peace Symbol
🕎 Menorah
🔯 Dotted Six-Pointed Star
♈ Aries
♉ Taurus
♊ Gemini
♋ Cancer
♌ Leo
♍ Virgo
♎ Libra
♏ Scorpio
♐ Sagittarius
♑ Capricorn
♒ Aquarius
♓ Pisces
⛎ Ophiuchus
🔀 Shuffle Tracks Button
🔁 Repeat Button
🔂 Repeat Single Button
▶️ Play Button
⏩ Fast-Forward Button
⏭️ Next Track Button
⏯️ Play or Pause Button
◀️ Reverse Button
⏪ Fast Reverse Button
⏮️ Last Track Button
🔼 Upwards Button
⏫ Fast Up Button
🔽 Downwards Button
⏬ Fast Down Button
⏸️ Pause Button
⏹️ Stop Button
⏺️ Record Button
⏏️ Eject Button
🎦 Cinema
🔅 Dim Button
🔆 Bright Button
📶 Antenna Bars
📳 Vibration Mode
📴 Mobile Phone Off
♀️ Female Sign
♂️ Male Sign
✖️ Multiply
➕ Plus
➖ Minus
➗ Divide
🟰 Heavy Equals Sign
♾️ Infinity
‼️ Double Exclamation Mark
⁉️ Exclamation Question Mark
❓ Red Question Mark
❔ White Question Mark
❕ White Exclamation Mark
❗ Red Exclamation Mark
〰️ Wavy Dash
💱 Currency Exchange
💲 Heavy Dollar Sign
⚕️ Medical Symbol
♻️ Recycling Symbol
⚜️ Fleur-de-lis
🔱 Trident Emblem
📛 Name Badge
🔰 Japanese Symbol for Beginner
⭕ Hollow Red Circle
✅ Check Mark Button
☑️ Check Box with Check
✔️ Check Mark
❌ Cross Mark
❎ Cross Mark Button
➰ Curly Loop
➿ Double Curly Loop
〽️ Part Alternation Mark
✳️ Eight-Spoked Asterisk
✴️ Eight-Pointed Star
❇️ Sparkle
©️ Copyright
®️ Registered
™️ Trade Mark
#️⃣ Keycap Number Sign
*️⃣ Keycap Asterisk
0️⃣ Keycap Digit Zero
1️⃣ Keycap Digit One
2️⃣ Keycap Digit Two
3️⃣ Keycap Digit Three
4️⃣ Keycap Digit Four
5️⃣ Keycap Digit Five
6️⃣ Keycap Digit Six
7️⃣ Keycap Digit Seven
8️⃣ Keycap Digit Eight
9️⃣ Keycap Digit Nine
🔟 Keycap: 10
🔠 Input Latin Uppercase
🔡 Input Latin Lowercase
🔢 Input Numbers
🔣 Input Symbols
🔤 Input Latin Letters
🅰️ A Button (Blood Type)
🆎 AB Button (Blood Type)
🅱️ B Button (Blood Type)
🆑 CL Button
🆒 Cool Button
🆓 Free Button
ℹ️ Information
🆔 ID Button
Ⓜ️ Circled M
🆕 New Button
🆖 NG Button
🅾️ O Button (Blood Type)
🆗 OK Button
🅿️ P Button
🆘 SOS Button
🆙 Up! Button
🆚 Vs Button
🈁 Japanese “Here” Button
🈂️ Japanese “Service Charge” Button
🈷️ Japanese “Monthly Amount” Button
🈶 Japanese “Not Free of Charge” Button
🈯 Japanese “Reserved” Button
🉐 Japanese “Bargain” Button
🈹 Japanese “Discount” Button
🈚 Japanese “Free of Charge” Button
🈲 Japanese “Prohibited” Button
🉑 Japanese “Acceptable” Button
🈸 Japanese “Application” Button
🈴 Japanese “Passing Grade” Button
🈳 Japanese “Vacancy” Button
㊗️ Japanese “Congratulations” Button
㊙️ Japanese “Secret” Button
🈺 Japanese “Open for Business” Button
🈵 Japanese “No Vacancy” Button
🔴 Red Circle
🟠 Orange Circle
🟡 Yellow Circle
🟢 Green Circle
🔵 Blue Circle
🟣 Purple Circle
🟤 Brown Circle
⚫ Black Circle
⚪ White Circle
🟥 Red Square
🟧 Orange Square
🟨 Yellow Square
🟩 Green Square
🟦 Blue Square
🟪 Purple Square
🟫 Brown Square
⬛ Black Large Square
⬜ White Large Square
◼️ Black Medium Square
◻️ White Medium Square
◾ Black Medium-Small Square
◽ White Medium-Small Square
▪️ Black Small Square
▫️ White Small Square
🔶 Large Orange Diamond
🔷 Large Blue Diamond
🔸 Small Orange Diamond
🔹 Small Blue Diamond
🔺 Red Triangle Pointed Up
🔻 Red Triangle Pointed Down
💠 Diamond with a Dot
🔘 Radio Button
🔳 White Square Button
🔲 Black Square Button
EOF
